.\"
.\" Copyright (c) 2011-2026 David Demelier <markand@malikania.fr>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt STRIS 6
.Os
.Sh NAME
.Nm stris
.Nd simple tetris
.Sh DESCRIPTION
The
.Nm
game is a simple tetris. It has a standard mode and two additional modes with
custom shapes.
.Pp
The game shows a colored background that changes over the number of lines
scored by the player.
.Pp
The following keys are used to control the game:
.Bl -tag
.It Sy Up
Rotate shape clockwise.
.It Sy Left
Move shape to the left.
.It Sy Right
Move shape to the right
.It Sy Down
Move shape one time down.
.It Sy Escape
Go to the previous menu, enter pause or exit the game.
.It Sy Return
Rotate the shape clockwise, select the menu entry.
.It Sy Space
Drop the shape.
.El
.Pp
Arrow keys are also used to navigate the menus.
.Sh SCORES
The
.Nm
game saves high scores globally on the system so that all users on the same
machine can compete between each others. Depending on the system, the scores
location varies.
.Ss Windows
On Windows, the score files are located into the
.Pa C:/Program Data
directory.
.Ss macOS
On macOS, when run inside a bundle application the scores are located inside
the application bundle using a world writable file. If ran as a standalone
executable it follows the same rules as UNIX (see below).
.Ss Other UNIXes
On every other platforms, the path to the scores is shared at
.Pa @VARDIR@/db/stris
directory.
.Sh AUTHORS
The
.Nm
game was written by
.An David Demelier Aq Mt markand@malikania.fr .
